name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
  workflow_dispatch:

permissions:
  contents: read
  packages: write   # <-- add this

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert repository owner to lowercase
        id: repo_owner
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.repo_owner.outputs.owner }}/playwright-scraper:latest
