name: Update FSTV Channels

on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: '0 */1 * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
      env:
        HOME: /root   # Fix Firefox/Chromium sandbox issues
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install python3-venv
        run: |
          apt-get update
          apt-get install -y python3-venv

      - name: Set up Python virtual environment and install deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install playwright==1.55.0
        shell: bash

      - name: Download Python script from Dropbox
        run: |
          curl -L -o FSTV_Scraper.py "https://www.dropbox.com/scl/fi/ib43qfg98l90qav4o0j30/fstvchannels.py?rlkey=3otbpfjtibho24guti8l5szsq&st=q0w05kiu&dl=1"
        shell: bash

      # Upload the script as artifact (can comment out later)
      - name: Upload FSTV_Scraper.py as artifact
        uses: actions/upload-artifact@v4
        with:
          name: FSTV_Scraper
          path: FSTV_Scraper.py

      - name: Run FSTV_Scraper to generate playlist
        run: |
          export HOME=/root
          source venv/bin/activate
          python FSTV_Scraper.py
        shell: bash

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: FSTVChannels.m3u
          DEST_PATH: /MyStuff/FSTVChannels.m3u
