name: Update F S T

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiohttp dropbox
          playwright install --with-deps firefox

      - name: Create Python script from secret
        env:
          FST_SCRIPT: ${{ secrets.FST_SCRIPT }}
        run: |
          echo "$FST_SCRIPT" > FST_SCRIPT.py

      - name: Run FST_SCRIPT with fallback URLs
        id: run_script
        run: |
          set -e
          if python FST_SCRIPT.py "https://fstv.space/?timezone=Australia%2FSydney"; then
            echo "Primary URL worked"
          else
            echo "Primary failed, trying fallback..."
            python FST_SCRIPT.py "https://fstv.zip/?timezone=Asia%2FTokyo"
          fi

          # Check if the playlist file was created
          if [ -f "FST_playlist.m3u" ]; then
            echo "Playlist file generated."
          else
            echo "Playlist file not found. Skipping Dropbox upload."
            echo "playlist_generated=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        if: steps.run_script.outputs.playlist_generated != 'false'
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: FST_playlist.m3u
          DEST_PATH: /MyStuff/FST_playlist.m3u
