name: Scraper Script MeaU

on:
  # Runs every 3 hours
  schedule:
    - cron: '0 */3 * * *'
  # Allow manual runs too
  workflow_dispatch:

jobs:
  run-media4u-script:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl
          pip install --upgrade pip
          pip install requests tqdm
        shell: bash

      - name: Download Media4u Scraper script
        run: |
          echo "📥 Downloading Meau.py from Dropbox..."
          curl -L -o Meau.py "https://www.dropbox.com/scl/fi/j4si6889xv9g0mn4v0n76/MEAU.py?rlkey=9wt4uegta8xq2vg4vj94bxh58&st=ch9qtdbc&dl=1"
        shell: bash

      - name: Run Scraper and Verify Output ⏱️
        run: |
          echo "::group::▶️ Running Meau.py..."
          START_TIME=$(date +%s)
          python Meau.py
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "::endgroup::"
          echo "::notice title=Script Time Complete::**✅ Meau.py FINISHED!** Time Taken: **${DURATION} seconds**"

          # Verify Mediauu.m3u
          if [ -f "Mediauu.m3u" ]; then
              echo "✅ Output file Mediauu.m3u found."
          else
              echo "❌ Expected output file Mediauu.m3u not found."
              exit 1 
          fi
        shell: bash

      - name: Upload Mediauu.m3u to Dropbox ⬆️
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: Mediauu.m3u
          DEST_PATH: /MyStuff/Mediauu.m3u
