name: PLTorr Playlist Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs exactly every hour

jobs:
  update-PLTorr-playlist:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
    env:
      HOME: /root
      DOCKER_CONFIG: /tmp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          apt-get update
          apt-get install -y python3-venv curl
          python3 -m venv venv
          source venv/bin/activate
          pip install playwright==1.55.0 httpx
          playwright install firefox
        shell: bash

      - name: Download Scraper
        run: |
          curl -L -o "$GITHUB_WORKSPACE/PLTorr.py" "https://www.dropbox.com/scl/fi/cum2szmskd5d3j2i4780y/PlayT.py?rlkey=4lazxrxj3w1446z4omar1l0m9&st=bdhont5f&dl=1"
        shell: bash

      - name: Run Scraper
        run: |
          source venv/bin/activate
          cd "$GITHUB_WORKSPACE"
          # Run the Playwright script to generate PLTorr.m3u
          python PLTorr.py
        shell: bash

      - name: Verify File Generation
        run: |
          cd "$GITHUB_WORKSPACE"
          if [ -f "PLTorr.m3u" ]; then
            echo "✅ PLTorr.m3u successfully generated."
            ls -lh PLTorr.m3u
          else
            echo "❌ ERROR: PLTorr.m3u was not created!"
            ls -R
            exit 1
          fi
        shell: bash

      - name: Upload Main Playlist to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: PLTorr.m3u 
          DEST_PATH: /MyStuff/PLTorr.m3u
