name: Update PPV

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright httpx aiohttp
          playwright install --with-deps firefox # Prioritize Firefox
          # If Firefox is not available or fails, it will fall back to chromium in the script

      - name: Create Python script from secret
        env:
          PPL_SCRIPT: ${{ secrets.PPL_SCRIPT }} # Use the secret containing the script
        run: |
          echo "$PPL_SCRIPT" > master_script.py # Save the secret content to a file

      - name: Run Python script to generate playlist
        run: |
          python master_script.py > PPV.m3u8 # Run the script and redirect its stdout to PPV.m3u8

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: PPV.m3u8
          DEST_PATH: /MyStuff/PPV.m3u8
