name: Update PPV

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright httpx aiohttp
          playwright install --with-deps firefox # <-- Installs Firefox browser

      - name: Create Python script from secret
        env:
          PPL_SCRIPT: ${{ secrets.PPL_SCRIPT }} # <-- Name of the secret holding your script
        run: |
          echo "$PPL_SCRIPT" > ppl_script.py # <-- Creates the script file

      - name: Run Python script
        run: |
          python ppl_script.py > PPV.m3u8 # <-- Runs the script and saves output to PPV.m3u8

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: PPV.m3u8
          DEST_PATH: /MyStuff/PPV.m3u8
