name: Update P P V

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble  # Includes Playwright + browsers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install python3-venv
        run: |
          apt-get update
          apt-get install -y python3-venv

      - name: Set up Python virtual environment and install deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install playwright==1.55.0 aiohttp dropbox
          playwright install
        shell: bash

      - name: Create Python script from secret
        env:
          PPL_SCRIPT: ${{ secrets.PPL_SCRIPT }}
        run: |
          echo "$PPL_SCRIPT" > PPL_SCRIPT.py

      # Upload the script as artifact for troubleshooting
      - name: Upload PPL_SCRIPT.py as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PPL_SCRIPT
          path: PPL_SCRIPT.py

      - name: Run PPL_SCRIPT to generate playlist
        id: run_script
        run: |
          source venv/bin/activate
          python PPL_SCRIPT.py
          if [ -f "PPV_playlist.m3u" ]; then
            echo "Playlist file generated."
          else
            echo "Playlist file not found. Skipping Dropbox upload."
            echo "playlist_generated=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        if: steps.run_script.outputs.playlist_generated != 'false'
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: PPV_playlist.m3u
          DEST_PATH: /MyStuff/PPV_playlist.m3u
