name: Playwright Scraper

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: ~/.cache/ms-playwright

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Cache Python packages (pip)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-1.55.0
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (only once, then cached)
        run: |
          pip install -r requirements.txt
          playwright install --with-deps firefox

      - name: Run scraper
        run: python PPL_SCRIPT.py
