name: Update P P V

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiohttp dropbox

      # ✅ Download and unpack Playwright standalone bundle (includes Node, browsers)
      - name: Download Playwright Standalone
        run: |
          curl -L -o playwright-standalone.zip \
            https://github.com/rgl/playwright-standalone/releases/latest/download/playwright-standalone-ubuntu.zip
          unzip -q playwright-standalone.zip -d playwright-standalone
          echo "$PWD/playwright-standalone" >> $GITHUB_PATH

      - name: Create Python script from secret
        env:
          PPL_SCRIPT: ${{ secrets.PPL_SCRIPT }}
        run: echo "$PPL_SCRIPT" > PPL_SCRIPT.py

      - name: Run PPL_SCRIPT to generate playlist
        id: run_script
        run: |
          python PPL_SCRIPT.py
          if [ -f "PPV_playlist.m3u" ]; then
            echo "playlist_generated=true" >> $GITHUB_OUTPUT
            echo "Playlist file generated."
          else
            echo "playlist_generated=false" >> $GITHUB_OUTPUT
            echo "Playlist file not found. Skipping Dropbox upload."
          fi
        shell: bash

      - name: Upload file to Dropbox
        if: steps.run_script.outputs.playlist_generated == 'true'
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: PPV_playlist.m3u
          DEST_PATH: /MyStuff/PPV_playlist.m3u
