name: Run Playwright Scripts MAIN (Debug)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    container:
      # ✅ Hardcoded lowercase repo owner to avoid invalid reference errors
      image: ghcr.io/kipkoechvictor3/playwright-scraper:latest
      options: --user root
    permissions:
      contents: write

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -al

      - name: Print master script
        run: cat master_script.py

      - name: Write scripts from secrets (sanitize NBSP)
        run: |
          echo "${FSTVL_SCRIPT}"        | sed 's/\xC2\xA0/ /g' > FSTVL_temp.py
          echo "${PPV_SCRIPT}"          | sed 's/\xC2\xA0/ /g' > PPV_temp.py
          echo "${WEARECHECKING_SCRIPT}"| sed 's/\xC2\xA0/ /g' > WeAreChecking_temp.py
          echo "${STREAMBTW_SCRIPT}"    | sed 's/\xC2\xA0/ /g' > StreamBtw_temp.py
          echo "${OVOGOALS_SCRIPT}"     | sed 's/\xC2\xA0/ /g' > OvoGoals_temp.py
          echo "${LocalChannels}"       | sed 's/\xC2\xA0/ /g' > LocalChannels_temp.py
        env:
          FSTVL_SCRIPT: ${{ secrets.FSTVL_SCRIPT }}
          PPV_SCRIPT: ${{ secrets.PPV }}
          WEARECHECKING_SCRIPT: ${{ secrets.WEARECHECKING_SCRIPT }}
          STREAMBTW_SCRIPT: ${{ secrets.STREAMBTW_SCRIPT }}
          OVOGOALS_SCRIPT: ${{ secrets.OVOGOALS_SCRIPT }}
          LocalChannels: ${{ secrets.LOCALCHANNELS }}

      - name: Run master script
        run: python master_script.py
        env:
          FSTVL_SCRIPT: ${{ secrets.FSTVL_SCRIPT }}
          PPV_SCRIPT: ${{ secrets.PPV }}
          WEARECHECKING_SCRIPT: ${{ secrets.WEARECHECKING_SCRIPT }}
          STREAMBTW_SCRIPT: ${{ secrets.STREAMBTW_SCRIPT }}
          OVOGOALS_SCRIPT: ${{ secrets.OVOGOALS_SCRIPT }}
          LocalChannels: ${{ secrets.LOCALCHANNELS }}

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: MyStuff/MyStuff.m3u
          DEST_PATH: /MyStuff/MyStuff.m3u
