name: Update TIM

on:
  workflow_dispatch:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble
      env:
        HOME: /root  # Fix Firefox/Chromium sandbox issues
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install python3-venv
        run: |
          apt-get update
          apt-get install -y python3-venv

      - name: Set up Python virtual environment and install deps
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install playwright==1.55.0 httpx
        shell: bash

      - name: Create Python script from secret
        env:
          TIM_SCRIPT: ${{ secrets.TIMST }}
        run: |
          echo "$TIM_SCRIPT" > TIM_Scraper.py

      # Upload the script as artifact (commented out for now)
      - name: Upload TIM_Scraper.py as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TIM_Scraper
          path: TIM_Scraper.py

      - name: Run Python script to generate playlist
        run: |
          export HOME=/root
          source venv/bin/activate
          python TIM_Scraper.py
        shell: bash

      - name: Upload file to Dropbox
        uses: gomes042/gh-actions-dropbox/files/upload@23ce81287e83f01c19c9f60b1849b746db6616b5
        with:
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source_path: Tim.m3u8
          DEST_PATH: /MyStuff/Tim.m3u8
